### ISSUE TITLE
Initialization failure when InfluxDB is not configured

### ISSUE THREAD

**Issue by trickv** [DerOetzi/solaredge2mqtt#47]
Hopefully a simple one. InfluxDB is optional (I'm not using it), but I've found that you have to have some bit of config stub else the initialization routine throws an error while trying to set the time zone on the influxdb client.

Example simple config:
```
$ cat .env
SE2MQTT_LOGGING_LEVEL=DEBUG
SE2MQTT_MODBUS__HOST=solaredge-inverter
SE2MQTT_MQTT__BROKER=litecoin
SE2MQTT_MQTT__USERNAME=anonymous
SE2MQTT_MQTT__PASSWORD=x
SE2MQTT_MQTT__TOPIC_PREFIX=solaredge
TZ=America/Chicago

```

When I run:
```
$ python -m solaredge2mqtt
2024-03-21 06:48:54.226 | DEBUG    | solaredge2mqtt.service:__init__:43 - interval=5 logging_level=DEBUG modbus=ModbusSettings(host='solaredge-inverter', port=1502, timeout=1, unit=1) mqtt=MQTTSettings(client_id='solaredge2mqtt', broker='litecoin', port=1883, username='anonymous', password=SecretStr('**********'), topic_prefix='solaredge') location=None prices=PriceSettings(consumption=None, delivery=None) monitoring=None wallbox=None influxdb=None weather=None forecast=None
2024-03-21 06:48:54.227 | INFO     | solaredge2mqtt.mqtt:__init__:15 - Using MQTT broker: litecoin:1883
2024-03-21 06:48:54.228 | INFO     | solaredge2mqtt.service.modbus:__init__:25 - Using SolarEdge inverter via modbus: solaredge-inverter:1502
2024-03-21 06:48:54.229 | INFO     | solaredge2mqtt.service:main_loop:89 - Starting SolarEdge2MQTT service...
2024-03-21 06:48:54.229 | INFO     | solaredge2mqtt.service:main_loop:90 - Version: 1.0.2
2024-03-21 06:48:54.229 | DEBUG    | solaredge2mqtt.service:main_loop:91 - interval=5 logging_level=DEBUG modbus=ModbusSettings(host='solaredge-inverter', port=1502, timeout=1, unit=1) mqtt=MQTTSettings(client_id='solaredge2mqtt', broker='litecoin', port=1883, username='anonymous', password=SecretStr('**********'), topic_prefix='solaredge') location=None prices=PriceSettings(consumption=None, delivery=None) monitoring=None wallbox=None influxdb=None weather=None forecast=None
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/trick/src/github.com/DerOetzi/solaredge2mqtt/solaredge2mqtt/__main__.py", line 4, in <module>
    run()
  File "/home/trick/src/github.com/DerOetzi/solaredge2mqtt/solaredge2mqtt/service/__init__.py", line 33, in run
    loop.run_until_complete(service.main_loop())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/trick/src/github.com/DerOetzi/solaredge2mqtt/solaredge2mqtt/service/__init__.py", line 92, in main_loop
    logger.info("Timezone: {timezone}", timezone=self.settings.influxdb.timezone)

```

My workaround is to add to my config file: `SE2MQTT_INFLUXDB__HOST=foo` which is enough config to instantiate the influxdb connector.

**Comment by trickv** [comment]
Fixed in v1.0.3
